# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Ubuntu 18.04 LTS (Bento)
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_version = "201806.08.0"
  
  # Provisioning.
  config.vm.provision "shell", path: "provision.sh"

  # Configure network.
  config.vm.network "private_network", ip: "192.168.10.150"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 8443
  
  config.vm.provider :virtualbox do |vb|
    # Set name of VM
    vb.name = "basephp-core.vm"
    
    # Increase the amount of memory to 1/4 of system memory.
    host = RbConfig::CONFIG['host_os']
    if host =~ /darwin/
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024
    elsif host =~ /linux/
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i
    elsif host =~ /mswin|mingw|cygwin/
      # Windows code via https://github.com/rdsubhas/vagrant-faster
      mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
    end
    mem = mem / 1024 / 4
    vb.customize ["modifyvm", :id, "--memory", mem]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.synced_folder "..", "/home/vagrant/www/basephp-core"
  config.vm.synced_folder '.', '/vagrant'
end
